# Generated by Django 3.1.7 on 2021-03-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_department_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
